#!/usr/bin/env bash
# =============================================================================
# scripts/setup-dev.sh
# Frontline Phase 1 — Local dev bootstrap
#
# Usage:
#   bash scripts/setup-dev.sh your@email.com "Your Full Name"
#
# Prerequisites:
#   - Docker running
#   - supabase start has been executed (supabase CLI ≥ 2.x)
#   - You have already signed up through the app (or will do so after running)
#
# What this does:
#   1. Parses supabase status output for all credentials
#   2. Writes backend/.env
#   3. Writes frontend/.env.local
#   4. Creates the default organisation "Sprout Retail"
#   5. Creates/updates your profile with admin role
# =============================================================================

set -euo pipefail

ADMIN_EMAIL="${1:-}"
ADMIN_NAME="${2:-Admin}"

if [[ -z "$ADMIN_EMAIL" ]]; then
  echo "❌  Usage: bash scripts/setup-dev.sh your@email.com \"Your Name\""
  exit 1
fi

echo ""
echo "🌱 Frontline — Dev Bootstrap"
echo "────────────────────────────────────────"

# ── Step 1: Read supabase status ──────────────────────────────────────────────
echo "📡 Reading Supabase credentials from 'supabase status'..."

SUPABASE_STATUS=$(supabase status 2>&1) || {
  echo "❌  'supabase status' failed. Is Docker running and 'supabase start' done?"
  exit 1
}

# Parse values using grep + awk
API_URL=$(echo "$SUPABASE_STATUS"         | grep "API URL"            | awk '{print $NF}')
ANON_KEY=$(echo "$SUPABASE_STATUS"        | grep "anon key"           | awk '{print $NF}')
SERVICE_ROLE_KEY=$(echo "$SUPABASE_STATUS" | grep "service_role key"  | awk '{print $NF}')
JWT_SECRET=$(echo "$SUPABASE_STATUS"      | grep "JWT secret"         | awk '{print $NF}')
DB_URL=$(echo "$SUPABASE_STATUS"          | grep "DB URL"             | awk '{print $NF}')

# Validate all required vars were parsed
MISSING=()
[[ -z "$API_URL"           ]] && MISSING+=("API_URL")
[[ -z "$ANON_KEY"          ]] && MISSING+=("ANON_KEY")
[[ -z "$SERVICE_ROLE_KEY"  ]] && MISSING+=("SERVICE_ROLE_KEY")
[[ -z "$JWT_SECRET"        ]] && MISSING+=("JWT_SECRET")
[[ -z "$DB_URL"            ]] && MISSING+=("DB_URL")

if [[ ${#MISSING[@]} -gt 0 ]]; then
  echo "❌  Could not parse the following from 'supabase status': ${MISSING[*]}"
  echo "    Run 'supabase status' manually and check the output format."
  exit 1
fi

echo "   ✓ API URL:           $API_URL"
echo "   ✓ Anon key:          ${ANON_KEY:0:20}..."
echo "   ✓ Service role key:  ${SERVICE_ROLE_KEY:0:20}..."
echo "   ✓ JWT secret:        ${JWT_SECRET:0:10}..."
echo "   ✓ DB URL:            $DB_URL"

# ── Step 2: Write backend/.env ────────────────────────────────────────────────
echo ""
echo "📝 Writing backend/.env..."

mkdir -p backend

BACKEND_SECRET=$(openssl rand -hex 32)

cat > backend/.env << EOF
# Auto-generated by scripts/setup-dev.sh — do not commit
SUPABASE_URL=${API_URL}
SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
SUPABASE_JWT_SECRET=${JWT_SECRET}
DATABASE_URL=${DB_URL}
BACKEND_SECRET_KEY=${BACKEND_SECRET}
ALLOWED_ORIGINS=http://localhost:3000
ENVIRONMENT=development
EOF

echo "   ✓ backend/.env written"

# ── Step 3: Write frontend/.env.local ─────────────────────────────────────────
echo ""
echo "📝 Writing frontend/.env.local..."

mkdir -p frontend

cat > frontend/.env.local << EOF
# Auto-generated by scripts/setup-dev.sh — do not commit
NEXT_PUBLIC_SUPABASE_URL=${API_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
EOF

echo "   ✓ frontend/.env.local written"

# ── Step 4: Create default organisation ───────────────────────────────────────
echo ""
echo "🏢 Creating default organisation 'Sprout Retail'..."

psql "$DB_URL" -q << 'EOSQL'
INSERT INTO organisations (name, slug)
VALUES ('Sprout Retail', 'sprout-retail')
ON CONFLICT (slug) DO NOTHING;
EOSQL

ORG_ID=$(psql "$DB_URL" -t -c "SELECT id FROM organisations WHERE slug = 'sprout-retail' LIMIT 1;" | tr -d ' \n')

if [[ -z "$ORG_ID" ]]; then
  echo "❌  Could not retrieve organisation ID after insert."
  exit 1
fi

echo "   ✓ Organisation ID: $ORG_ID"

# ── Step 5: Look up auth user and create/update profile ───────────────────────
echo ""
echo "👤 Setting up admin profile for: $ADMIN_EMAIL"

# Look up the auth user ID
AUTH_USER_ID=$(psql "$DB_URL" -t -c \
  "SELECT id FROM auth.users WHERE email = '${ADMIN_EMAIL}' LIMIT 1;" | tr -d ' \n')

if [[ -z "$AUTH_USER_ID" ]]; then
  echo "⚠️   No auth user found for $ADMIN_EMAIL."
  echo "    Sign up through the app first, then re-run this script."
  echo ""
else
  # Upsert the profile row
  psql "$DB_URL" -q << EOSQL
INSERT INTO profiles (id, organisation_id, full_name, role)
VALUES (
  '${AUTH_USER_ID}',
  '${ORG_ID}',
  '${ADMIN_NAME}',
  'admin'
)
ON CONFLICT (id) DO UPDATE SET
  organisation_id = EXCLUDED.organisation_id,
  full_name = EXCLUDED.full_name,
  role = 'admin',
  updated_at = now();
EOSQL

  # Update auth.users app_metadata so JWT contains org + role
  psql "$DB_URL" -q << EOSQL
UPDATE auth.users
SET raw_app_meta_data = raw_app_meta_data
  || jsonb_build_object('organisation_id', '${ORG_ID}', 'role', 'admin')
WHERE id = '${AUTH_USER_ID}';
EOSQL

  echo "   ✓ Profile created/updated with role: admin"
fi

# ── Done ───────────────────────────────────────────────────────────────────────
echo ""
echo "────────────────────────────────────────"
echo "✅  Setup complete!"
echo ""
echo "Next steps:"
echo "  Terminal 1 — Backend:"
echo "    cd backend && python -m venv .venv && source .venv/bin/activate"
echo "    pip install -r requirements.txt"
echo "    uvicorn main:app --reload --port 8000"
echo ""
echo "  Terminal 2 — Frontend:"
echo "    cd frontend && npm install && npm run dev"
echo ""
echo "  Then open: http://localhost:3000/login"
if [[ -z "$AUTH_USER_ID" ]]; then
  echo "  → Sign up first, then re-run this script to get admin access."
fi
echo ""
